add controller
noslate-project/noslated pull request #7
Opened 2022-10-20 07:21 UTC by umuoy1

1. 增加控制器的概念
1.1 将 `capacity_manager` 中控制逻辑迁移到控制器中
1.2 将扩缩容流程分离到不同控制器中
1.3 聚合扩容指标的计算流程
2. 增加状态管理模块，提供 `syncWorkerData`, `updateContainerStatusByReport` 等方法

2022-10-20 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/noslate-project/noslated?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/noslate-project/noslated?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/noslate-project/noslated?pullRequest=7) it.</sub>

2022-10-25 06:07 UTC, mariodu approved these changes

2022-10-25 06:07 UTC, mariodu commented on src/control_plane/worker_stats/worker.ts
> +    return this.#latestUpdateContainerStatusTimestamp;
时间戳不用了，performance.now() 虽然高精度，但是跨进程有问题，只保证单调性，暂时没有可供比较的高精时间戳实现。
就在改变状态时打印一下作为记录吧，不作为限制条件

2022-10-25 06:07 UTC, mariodu commented on src/control_plane/data_plane_client/subscription.ts
> +
subscription 里别放这么多逻辑吧，交由具体的模块去执行吧

2022-10-25 06:07 UTC, mariodu commented on src/control_plane/__test__/worker_stats/state_manager.test.ts
> +            functionProfileManager.set([{
上面初始化了 agent，用 agent set function profile 不就可以了吗

2022-10-25 06:07 UTC, mariodu commented on src/control_plane/__test__/worker_stats/state_manager.test.ts
> +            assert.strictEqual(worker.containerStatus, ContainerStatus.Unknown);
Stopped 属于一种终止状态了，Unknown 也属于终止状态，理论上不存在 Stopped -> Unknown 的过渡，代码里防止下吧

2022-10-25 06:07 UTC, mariodu commented on src/control_plane/__test__/worker_stats/state_manager.test.ts
> +            await turf.create('worker1', simpleSandbox);
mock 了 worker stats，还要启动 worker 嘛？

2022-10-25 06:07 UTC, mariodu commented on src/control_plane/__test__/worker_stats/state_manager.test.ts
> +            const beforeSync = controlPlane.capacityManager.workerStatsSnapshot.getBroker('func1', false)?.getWorker('worker1')?.toJSON();
一定存在用 ! 吧

2022-10-26 08:09 UTC, umuoy1 commented on src/control_plane/__test__/worker_stats/state_manager.test.ts
> +            await turf.create('worker1', simpleSandbox);
这里想用真实的 worker 状态数据测试 syncWorkerData

2022-10-26 10:01 UTC, mariodu requested changes

2022-10-26 10:01 UTC, mariodu commented on src/control_plane/data_plane_client/subscription.ts
> -    this.logger.info(`receive container status report: ${Date.now()}, ${report.requestId}, ${report.functionName}, ${report.name}, ${report.isInspector}, ${report.event}`);
这个日志记录一下

2022-10-26 10:01 UTC, mariodu commented on src/control_plane/worker_stats/state_manager.ts
> +  #setStatusToByEvent(event: string) {
这个不做 set 操作，方法名调整下？

2022-10-26 10:01 UTC, mariodu commented on src/control_plane/worker_stats/state_manager.ts
> +    worker.containerStatus = statusTo;
调用 worker 的方法设置，不要直接赋值

2022-11-07 09:28 UTC, mariodu approved these changes

2022-11-09 09:05 UTC, umuoy1 commented
http://ci.dragonwell-jdk.io/view/noslate/job/noslate-test-linux-x64/71/

2022-11-09 09:06 UTC, merged